version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${PORT}:5173"